In [1]:
import numpy as np 

## Задание 1

In [35]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

mean_a = np.array([np.mean(a, axis = 0)])

print(mean_a)

[[2.  8.4]]


## Задание 2

In [32]:
a_centered = np.subtract(a, mean_a)

In [34]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


## Задание 3

In [25]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [26]:
print(a_centered_sp)

8.0


In [27]:
N = a.shape[0]

In [28]:
print(N)

5


In [29]:
result = a_centered_sp/(N-1)
print(result)

2.0


## Задание 4

In [36]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])